### PR TITLE
updated discord.py and dotenv

### PR DESCRIPTION
**Pull request by mhiner**
* Updated dependencies to current.
* added intents required for discord.py 2.0
* removed context.message_typing since they were not required and caused crashes in the initiative function.

### CODE REVIEW

**Comment by MrMstislav** [comment]
Thanks for your contribution. I was under the impression slash commands were mandatory with the new API and mentions were going to be deprecated. Is that the case?

**Comment by mhiner** [comment]
> Thanks for your contribution. I was under the impression slash commands were mandatory with the new API and mentions were going to be deprecated. Is that the case?

To be honest, I do not know.  I can check and add another patch if that is the case but for this PR I was trying to minimize changes while still updating the dependencies and having the published functions operate.  (Only initiative had an issue after update)

**Comment by mikblack** [comment]
Slash commands are only required for bots that are in more than 100 servers (which is the threshold for getting the bot verified by Discord).  Non-verified bots can still use the old method of listening for messages.

**Comment by rpgmik** [comment]
Slash commands are only required for bots that are in more than 100 servers (which is the threshold for getting the bot verified by Discord). Non-verified bots can still use the old method of listening for messages.

Sorry for the double message - posted from the wrong GitHub account. 🤦‍♂️

**Comment by MrMstislav** [comment]
> Slash commands are only required for bots that are in more than 100 servers (which is the threshold for getting the bot verified by Discord). Non-verified bots can still use the old method of listening for messages.
> 
> Sorry for the double message - posted from the wrong GitHub account. 🤦‍♂️

Ah, makes sense, I guess discord's been nagging me since the original rendition of the bot was verified when I used to host it for free for everyone (it still feels unbelievable that there are/were that many games to reach the 100 mark). Unless someone plans on doing massive hosting I think we're in the safe. Thanks again for your contributions.

**Pull request merged**
